on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: A flake8 linter
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Lint
        id: lint
        uses: lukacat10/Flake8@v3
        with:
          path: 'src'
